### ISSUE TITLE
HI :)

### ISSUE THREAD

**Issue by L0RI-ORIGIN** [Sninctbur/BA2#2]
hi: D, I would like the complete source code because I would like to create a virus mod for me and my friends but I'm not a programmer :( can you help me? thanks

**Comment by Sninctbur** [comment]
There are lots of tutorials online that can get you started with the gist of programming. Once you think you have enough experience, you can flip through the code in this GitHub repository and try to figure out how it works. You'll want to use the Facepunch wiki a lot.

In the future, please use this section to report bugs and nothing else. This is not a second Workshop comments section.
