### ISSUE TITLE
Reducing the time it takes to remove a stuck zombie

### ISSUE THREAD

**Issue by Auditormadness9** [Sninctbur/BA2#4]
Hello. I wanted to ask what timer.simple function should I remove for it to never delay removing a stuck zombie (I want it to remove a zombie right when it cannot move towards my direction). I browsed the FP wiki a lot, know some functions, and actively browsed all the files and code of your addon (mainly ba2_hordespawner.lua and nb_ba2_infected.lua), tried removing the timer from the function that reads "ba2_hs_notargetclean", and also tried to remove every timer that has to do with HandleStuck(), even replaced every instance of HandleStuck() with OnStuck(), then Remove(), still nothing helped... and the delay is still there, and sometimes even a bug occurs when they don't get removed but get removed immediately when they get killed.

Any help would be amazingly appareciated!^^

**Comment by Sninctbur** [comment]
The timing of stuck detection is handled by Facepunch's CLuaLocomotion AI, not any functions added by BA2's nextbots. Being stuck is different from being unable to compute a path to the target; if that's when you want the zombie to delete itself, you'll want to look at line 377 where the pathComplete variable is used.

**Comment by Auditormadness9** [comment]
> The timing of stuck detection is handled by Facepunch's CLuaLocomotion AI, not any functions added by BA2's nextbots. Being stuck is different from being unable to compute a path to the target; if that's when you want the zombie to delete itself, you'll want to look at line 377 where the pathComplete variable is used.

Well at that line this is what my code looks like
![image](https://user-images.githubusercontent.com/71278545/154734530-dfdf54f2-4e9f-4085-a6ce-d350d0e65acc.png)

I'll try to add self:Remove() to where you said and test again, like this:

![image](https://user-images.githubusercontent.com/71278545/154735036-b0695d7a-d10f-4033-bc5c-ec9c91b85db3.png)

And yes, if I want it to be removed as soon as it's stuck (immediate removal), don't I have to override OnStuck() or HandleStuck()? I did that and it still didn't help, probably because it still calls the hook late because of how CLuaLocomotion handles it like you said. In that case, is there no way to modify the loco itself to not delay it?

An alternative method I'm thinking of is to also make a func that detects if it is colliding with anything (map or entity) and remove immediately.
