### ISSUE TITLE
Updating Jmod compatibility

### ISSUE THREAD

**Issue by AdventureBootCoder** [Sninctbur/BA2#7]
I wanted to let you know that the JMod compatibility has fallen out of date.
Jack, switched from `JMod_` to `JMod.` a while ago for organizational reasons and so the biological resistance method has changed names.
Here's how it would probably work now:
`BA2_JMod = istable(JMod) and JMod.GetArmorBiologicalResistance`
`if BA2_JMod and ent:IsPlayer() and JMod.GetArmorBiologicalResistance(ent, DMG_NERVEGAS) > 0 then`
I could write the required code changes if you want me to.

**Comment by Sninctbur** [comment]
Thank you for bringing this to my attention. If you would like to make a pull request for this, I will happily merge it.

**Comment by AdventureBootCoder** [comment]
Sure thing

**Comment by AdventureBootCoder** [comment]
Pull request open:
https://github.com/Sninctbur/BA2/pull/8
